Linear Regression

In [22]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression

In [2]:
df=pd.read_csv("../DATA_SCIENCE/Dataset/heart.csv")
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [4]:
X=df.drop("HeartDisease",axis=1)

In [5]:
X.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up

In [6]:
y=df["HeartDisease"]

In [7]:
y.head()

0    0
1    1
2    0
3    1
4    0
Name: HeartDisease, dtype: int64

In [14]:
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=5,train_size=0.8)

In [15]:
X_train

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope
810,55,F,ATA,135,250,0,LVH,161,N,1.4,Flat
467,63,F,ATA,132,0,0,Normal,130,N,0.1,Up
355,67,M,TA,145,0,0,LVH,125,N,0.0,Flat
478,57,M,ASY,130,311,1,ST,148,Y,2.0,Flat
631,46,M,ASY,140,311,0,Normal,120,Y,1.8,Flat
...,...,...,...,...,...,...,...,...,...,...,...
400,50,F,ASY,160,0,1,Normal,110,N,0.0,Flat
118,35,F,TA,120,160,0,ST,185,N,0.0,Up
701,62,M,ATA,128,208,1,LVH,140,N,0.0,Up
206,35,M,ATA,120,308,0,LVH,180,N,0.0,Up
867,44,M,ASY,112,290,0,LVH,153,N,0.0,Up

In [16]:
y_train

810    0
467    0
355    1
478    1
631    1
      ..
400    1
118    0
701    0
206    0
867    1
Name: HeartDisease, Length: 734, dtype: int64

In [23]:
LR=LinearRegression()

In [24]:
LR.fit(X_train,y_train)

ValueError: could not convert string to float: 'F'